### ISSUE TITLE
Uncaught Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by ghost** [dennorske/atom-pawn-build#9] opened 2020-09-19 10:22 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: [pawn-build](https://github.com/dennorske/atom-pawn-build) package 0.3.2

### Stack Trace

Uncaught Error: spawn UNKNOWN

```
At internal/child_process.js:371

Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:371:11)
    at Object.spawn (child_process.js:558:9)
    at Object.build (/packages/pawn-build/lib/pawn-build.js:114:35)
    at /packages/pawn-build/lib/pawn-build.js:51:38)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:349780)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:1231083)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:1227217)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:284829)
```

### Commands

```
  5x -4:14.7.0 core:backspace (input.hidden-input)
  2x -3:43.4.0 core:move-left (input.hidden-input)
     -3:42.2.0 core:backspace (input.hidden-input)
  2x -3:41.9.0 core:save (input.hidden-input)
  4x -3:37 pawn-build:build (input.hidden-input)
  6x -3:02.4.0 core:backspace (input.hidden-input)
     -2:58.5.0 core:save (input.hidden-input)
  3x -2:54.9.0 pawn-build:build (input.hidden-input)
  4x -1:25.6.0 core:move-right (input.hidden-input)
 12x -1:24.8.0 core:backspace (input.hidden-input)
     -1:23.1.0 core:save (input.hidden-input)
     -1:21.5.0 core:backspace (input.hidden-input)
     -1:20.9.0 core:save (input.hidden-input)
  2x -1:14.4.0 pawn-build:build (input.hidden-input)
     -0:54 core:save (input.hidden-input)
     -0:47.8.0 pawn-build:build (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
language-pawn 0.6.5 
pawn-build 0.3.2 
```

**Comment by dennorske** [comment] 2021-01-10 20:32
Unable to reproduce this one, so I'll close it for now..

**Closed as completed by dennorske** 2021-01-10 20:32 UTC
